#! /usr/bin/env ruby

require_relative 'lib/setup'
require_relative 'lib/importer/feed_importer'

episode_number = ENV.fetch('episode_number', nil).to_i
Importer::FeedImporter.import!(episode_number)

