#! /usr/bin/env ruby

#
# This script fetches the episode ID from the publishing service and prints the command to set the episode.
#
# Usage:
# service_name={publishing_service_name} episode_number={target_episode_number} set-episode-builder
#   publishing_service_name: apple, spotify
#   target_episode_number: 123, 124, 125, ...
#
# Example:
# service_name=apple episode_number=123 set-episode-builder
#
# Output:
# npm run set-episode --ep=123 --service=apple --id=1234567890
#
# You can copy the output and run it in the terminal to set the episode.
#
# Example:
# service_name=apple episode_number=123 set-episode-builder | sh

require_relative 'lib/publishing'
require_relative 'lib/publishing/service'
require_relative 'lib/publishing/service/apple'
require_relative 'lib/publishing/service/spotify'
require_relative 'lib/publishing/episode_fetcher'

service_name = ENV.fetch('service_name')
service = case service_name
          when 'apple' then Publishing::Service::Apple
          when 'spotify' then Publishing::Service::Spotify
          else raise "Unknown service: #{service_name}"
          end
episode_number = ENV.fetch('episode_number').to_i

episode_fetcher = Publishing::EpisodeFetcher.new(service)
episode_id = episode_fetcher.fetch.find { |episode| episode.number == episode_number }.id

puts "npm run set-episode --ep=#{episode_number} --service=#{service_name} --id=#{episode_id}"
